#include "helpers.h"
#include "spmm.h"

const char* spmm_get_error_name(SpmmStatus_t err)
{
	switch (err) {
	case SPMM_STATUS_SUCCESS:
		__builtin_unreachable();
	case SPMM_STATUS_NOT_INITIALIZED:
		return "SPMM_STATUS_NOT_INITIALIZED";
	case SPMM_STATUS_ALLOC_FAILED:
		return "SPMM_STATUS_ALLOC_FAILED";
	case SPMM_STATUS_INVALID_VALUE:
		return "SPMM_STATUS_INVALID_VALUE";
	case SPMM_STATUS_ARCH_MISMATCH:
		return "SPMM_STATUS_ARCH_MISMATCH";
	case SPMM_STATUS_MAPPING_ERROR:
		return "SPMM_STATUS_MAPPING_ERROR";
	case SPMM_STATUS_EXECUTION_FAILED:
		return "SPMM_STATUS_EXECUTION_FAILED";
	case SPMM_STATUS_INTERNAL_ERROR:
		return "SPMM_STATUS_INTERNAL_ERROR";
	case SPMM_STATUS_MATRIX_TYPE_NOT_SUPPORTED:
		return "SPMM_STATUS_MATRIX_TYPE_NOT_SUPPORTED";
	case SPMM_STATUS_ZERO_PIVOT:
		return "SPMM_STATUS_ZERO_PIVOT";
	case SPMM_STATUS_NOT_SUPPORTED:
		return "SPMM_STATUS_NOT_SUPPORTED";
	case SPMM_STATUS_INSUFFICIENT_RESOURCES:
		return "SPMM_STATUS_INSUFFICIENT_RESOURCES";
	default:
		__builtin_unreachable();
	}
}
